### ISSUE TITLE
Implement a more sophisticated privilege system

### ISSUE THREAD

**Issue by encratite** [encratite/RiotControl#35]
Right now the privilege system only recognises two modes, which are the "read-only" mode which does not even permit users to issue searches (since it is truly supposed to be a safe read-only environment where users can only view summoners they have been linked to that are already in the database), and the full "administrator" mode which enables users to issue searches, to update summoners and to toggle the automatic update flag on any summoner.

User "Poddo" on Reddit outlined his use case, which involves enabling everybody to issue searches so he doesn't have to manually make IPs of his friends privileged in the configuration file. I suggest two changes to address this:
1. Switch from a two level privilege system to a fully user-defined one with an arbitrary number of levels. Such a setup could look like this:

Administrator level: like trusted, but may also toggle the update flag on summoners
Trusted level: may issue new searches and may request manual updates on summoners
Visitor level: may only view existing summoners that are already in the database
1. Each one of these levels can be configured to either match a group of certain IPs or simply any IP (boolean catch-all toggle). The server then assigns each request to one of the levels by iterating over the levels and their filters, commencing with the ones the user defined first in the configuration file until one of them matches the request, based on IP filtering.

The permission mask for each user level will probably have to be defined in terms of the JSON API, which might be somewhat cryptic for most users, though, as it is not obvious what permissions they are editing.

Another problem with this is that it introduces backward incompatibility with old configuration files. I have already added one new "default value" in configuration files for the new RiotShield project that requires the introduction of support for multiple SQLite drivers. It would be ugly to accumulate things like these over time but it would be elegant to provide automatic updates of old data formats for the configuration file and the database.

A similar issue is the introduction of new tables in the database or even editing existing ones.

**Comment by Poddo** [comment]
I feel famous or something!  I've been thinking about this all day because I'm excited to roll this out to my close group of LoL friends, and come on here to see you made an issue. Your method of multiple levels is much more elegant than what my brain came up with.  

I'm not a developer of any sort, so this suggestion may be terrible, but could you avoid configuration file issues by having the newer versions of the program ignore the privileged section of the file and reference a separate, new "users.xml" (or something), that a newer version of the .exe would create upon runtime if it wasn't found?  This way the update process of copying the new .exe and .dlls remains the same.  I'm not sure if that's messier or more of a kludge than just adding a new line to configuration.xml, or trying to figure out a way to convert old configs to new ones.  Just something I was thinking about. However you end up going about it, I'm glad to see you taking suggestions from the community seriously!

**Comment by encratite** [comment]
Oh, that's not an issue, I can just have the application add default values automatically if they are undefined. The most severe backward compatibility issues are those that alter existing structures, such as the recent database modification.

**Comment by encratite** [comment]
Implemented in https://github.com/epicvrvs/RiotControl/commit/91295004b52f2b339c298f316f00284190ebf064
