### ISSUE TITLE
Cannot handle the LoL Server Login Queue

### ISSUE THREAD

**Issue by quentins** [encratite/RiotControl#66]
It appears that the Riot Control client just attempts to connect, over and over again, and it treats the login queue as a failure so it stops and tries again. This prevents it from getting to the end of the queue and ever logging in.

The following two messages repeat, and after and hour no connection was made:

2012-06-24 23:41:51 [NA AccountName] Connecting to the server
2012-06-24 23:41:53 [NA AccountName] The server has placed this client in the login queue. Please be patient.

**Comment by encratite** [comment]
It has never had proper login queue handling. It basically just keeps on trying until it gets in. It doesn't try to retrieve a login queue token and all that stuff. This was added to the Issues of LibOfLegends in the early days of the project but hasn't been addressed since because it worked fine. I'm too lazy to address this at this point, maybe somebody else feels like it.

I hope that they'll just fix the servers and then this will no longer be an issue :P

**Comment by Theoretical** [comment]
I might tackle it after work tonight.
