### ISSUE TITLE
(Not an issue) How do I obtain a user's summoner name based on their account credentials?

### ISSUE THREAD

**Issue by Apothems** [encratite/RiotControl#67]
I am sorry if this is not the place to ask, but I don't know how to contact anyone here.

Are you (the dev[s] of RiotControl) able to teach me how to get a LoL account's Summoner name (given their account + password) OR given a user's Summoner name, find out what their account name is using ONLY POST/GET HTTP requests? The latter case would be ideal for me, but if it's not possible then the prior case works just as well.

If possible, we can talk via e-mail or some instant messenger...

**Comment by encratite** [comment]
This belongs to LibOfLegends instead of RiotControl really. I am fairly certain that the latter is not possible without using other services that do the work for you (i.e. third parties, not using the Riot servers directly). I'm not entirely certain about the first case either. I presume you receive the account ID or something after you log in but the thing is that I have never looked for this data before.

**Comment by encratite** [comment]
Jabe said:

"You confirm your own ID with getLoginPacket.  You can get anyone's with getSummonerByName"
